apiVersion: v1
kind: Secret
metadata:
  name: moviesdb-secrets
  namespace: moviesdb
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"
  TMDB_API_KEY: ""
  OMDB_API_KEY: ""
